### ISSUE TITLE
Boost fails to build under macOS 10.15.6

### ISSUE THREAD

**Issue by lars20070** [OpenMS/contrib#102]
Under macOS 10.15.6 Boost fails to build
```
cmake -DBUILD_TYPE=ALL -DNUMBER_OF_JOBS=4 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang /Users/lars/Code/OpenMS-Release-2-5-0/OpenMS/contrib
```
with
```
clang: error: unknown argument: '-fcoalesce-templates'
```
See also [here](https://github.com/arvidn/libtorrent/issues/4662#issuecomment-630264529).

**Comment by lars20070** [comment]
I am running GCC 4.2.1 https://github.com/zcash/zcash/issues/4333

**Comment by oliveralka** [comment]
Do you use the current contrib? 

I think there was a patch for boost added recently by Julianus for XCode 11.4 
https://github.com/OpenMS/contrib/commit/b7883a520533928b6f8199ac58e0a549838ce8cd

I can build the current contrib without any issues.
macOS 10.15.6
Apple clang version 11.0.0 (clang-1100.0.33.8)

**Comment by lars20070** [comment]
macOS 10.15.6
Apple clang version 11.0.3 (clang-1103.0.32.62)

With the current contrib following the [build instructions](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/release/latest/html/install_mac.html).

**Comment by lars20070** [comment]
I was building Release 2.5.0 from 24/02/20. Hence the contrib submodule does not include the `b7883a5` patch from 22/04/20.
