### ISSUE TITLE
Do NOT use manylinux Dockerfile here!

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/contrib#116]
It uses the contrib version from the OpenMS submodule, which is of course not updated yet when you push here.
https://github.com/OpenMS/dockerfiles/blob/master/pyOpenMS/manylinux/Dockerfile#L16

**Comment by timosachsenberg** [comment]
Can you add some more hints what the proper way would be here. I can take a look after my vacation

**Comment by jpfeuffer** [comment]
Or just fix https://github.com/OpenMS/dockerfiles/issues/12

**Comment by jpfeuffer** [comment]
There has to be a contrib container and a contrib-openms-tested container
one is triggered for every push here.
The other for every push to OpenMS.

**Comment by jpfeuffer** [comment]
Or even better, let every PR here be tested against OpenMS immediately.
The whole logic should receive an update anyway.
You probably need a temporary archive for contrib artifacts, for every PR here.

**Comment by jpfeuffer** [comment]
Dozens of possibilities.

**Comment by jpfeuffer** [comment]
@timosachsenberg It makes even less sense now after moving.
https://github.com/OpenMS/contrib/blob/master/dockerfiles/pyopenms/manylinux/Dockerfile#L16

This is a blocker.

**Comment by timosachsenberg** [comment]
https://github.com/OpenMS/contrib/pull/128
