### ISSUE TITLE
Libraries missing on Win7 / MSVS 2008

### ISSUE THREAD

**Issue by hroest** [OpenMS/contrib#21]
When compiling with `cmake -DBUILD_TYPE=ALL  -G "NMake Makefiles ..\openms_contrib` on a Win7 machine (32 bit, MSVS 2008) I seem to be missing some libraries. 
1. I only get one Wildmagic library (`Wm5Cored.lib`) which is not what OpenMS later expects, see https://github.com/OpenMS/OpenMS/pull/2040
2. I seem to be missing `libboost_regex-vc90-mt-1_52.lib` which can be corrected by copying `libboost_regex-mt.lib` to that location. It seems some boost libs produce the "vc90-mt-1_52" libs by default (math) while others do not produce it and do not seem to need it for OpenMS (bzip2, date, iostreams, zlib). Unfortuntately regex does not produce it but seem to need it

**Comment by hroest** [comment]
using the above command, I get the following libraries:

```
 Volume in drive C has no label.
 Volume Serial Number is 32D9-EF9A

 Directory of C:\openms\win32_contrib_build6\lib

09.07.2016  22:00    <DIR>          .
09.07.2016  22:00    <DIR>          ..
07.07.2016  21:15         1'210'284 cblas.lib
07.07.2016  21:15         1'239'478 cblas_d.lib
07.07.2016  21:16         2'424'454 glpk.lib
07.07.2016  21:16         1'645'160 glpkd.lib
07.07.2016  21:15        16'842'054 gsl.lib
07.07.2016  21:15        18'166'374 gsl_d.lib
07.07.2016  21:10           378'710 libboost_bzip2-mt-gd.lib
07.07.2016  21:12            79'712 libboost_bzip2-mt.lib
07.07.2016  21:10         1'868'408 libboost_date_time-mt-gd.lib
07.07.2016  21:12           531'866 libboost_date_time-mt.lib
07.07.2016  21:10         2'392'420 libboost_iostreams-mt-gd.lib
07.07.2016  21:12           659'430 libboost_iostreams-mt.lib
07.07.2016  21:10         4'035'580 libboost_math_c99-mt-gd.lib
07.07.2016  21:12         1'391'480 libboost_math_c99-mt.lib
12.07.2016  21:32         1'391'480 libboost_math_c99-vc90-mt-1_52.lib
07.07.2016  21:11         4'054'416 libboost_math_c99f-mt-gd.lib
07.07.2016  21:12         1'405'614 libboost_math_c99f-mt.lib
12.07.2016  21:32         1'405'614 libboost_math_c99f-vc90-mt-1_52.lib
07.07.2016  21:11         3'995'180 libboost_math_c99l-mt-gd.lib
07.07.2016  21:12         1'369'446 libboost_math_c99l-mt.lib
12.07.2016  21:32         1'369'446 libboost_math_c99l-vc90-mt-1_52.lib
07.07.2016  21:10        13'922'078 libboost_math_tr1-mt-gd.lib
07.07.2016  21:12         5'662'068 libboost_math_tr1-mt.lib
12.07.2016  21:32         5'662'068 libboost_math_tr1-vc90-mt-1_52.lib
07.07.2016  21:10        14'448'688 libboost_math_tr1f-mt-gd.lib
07.07.2016  21:12         5'929'880 libboost_math_tr1f-mt.lib
12.07.2016  21:32         5'929'880 libboost_math_tr1f-vc90-mt-1_52.lib
07.07.2016  21:10        13'811'708 libboost_math_tr1l-mt-gd.lib
07.07.2016  21:12         5'609'864 libboost_math_tr1l-mt.lib
12.07.2016  21:32         5'609'864 libboost_math_tr1l-vc90-mt-1_52.lib
07.07.2016  21:11        34'538'006 libboost_regex-mt-gd.lib
07.07.2016  21:13        10'695'150 libboost_regex-mt.lib
07.07.2016  21:10           301'080 libboost_zlib-mt-gd.lib
07.07.2016  21:12           120'694 libboost_zlib-mt.lib
07.07.2016  21:05           259'954 libbz2d.lib
07.07.2016  21:22         4'186'298 libCbc.lib
07.07.2016  21:22        10'669'622 libCbcd.lib
07.07.2016  21:22         3'052'072 libCgl.lib
07.07.2016  21:22         8'384'514 libCgld.lib
07.07.2016  21:22         4'424'242 libClp.lib
07.07.2016  21:22        11'583'954 libClpd.lib
07.07.2016  21:22         3'435'356 libCoinUtils.lib
07.07.2016  21:22         8'987'740 libCoinUtilsd.lib
07.07.2016  21:22         1'260'380 libOsi.lib
07.07.2016  21:22           618'778 libOsiClp.lib
07.07.2016  21:22         1'331'840 libOsiClpd.lib
07.07.2016  21:22         3'452'726 libOsid.lib
07.07.2016  21:01            98'760 libsvmd.lib
07.07.2016  21:29         2'348'398 Wm5Cored.lib
07.07.2016  21:29        46'425'228 Wm5Mathematicsd.lib
07.07.2016  21:05         3'114'132 xerces-c_3.lib
07.07.2016  21:05         3'121'170 xerces-c_3D.lib
07.07.2016  21:05         1'888'768 xerces-c_3_1.dll
07.07.2016  21:05         3'914'752 xerces-c_3_1D.dll
07.07.2016  21:05           252'014 zlibd.lib
              56 File(s)    323'603'482 bytes
               2 Dir(s)  31'976'071'168 bytes free
```

so it seems that for the following libs only produce debug libraries

- Wildmagic 
- libSVM
- libbz2

and one has to manually go into the folder, and run  `cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles"  & nmake` in order to produce the correct release libs.

**Comment by cbielow** [comment]
Have you tried using the Vs Generator?  Internally Cmake seems to be doing something different (maybe because nmake only knows about release OR debug,  not both)...at least thats what i remember from back then. And nmake does not give any advantages here... the makefile is never used anyway. 

Other recent tickets seem also be related to nmake. The better tested alternative is to use vs Solution  files and call msbuild.exe on the command line if you must. See build.bat in /tools for shorthand notation.
I agree it's better to support all variants but maybe documenting this better is sufficient for now.. 
-- 
Sent via mobile phone.

Am 12. Juli 2016 22:31:29 MESZ, schrieb Hannes Roest <notifications@github.com>:

**Comment by hroest** [comment]
hmm ok, this may be part of the Problem here. I have used nmake to be consistent across all builds and because I only have a Express edition of visual studio with the compiler. I will try and use the other generator and see whether that helps.

**Comment by hroest** [comment]
yes, you are right, it works much better with the correct generator :-) 
sorry, I was so caught up in the all the problems on Windows that I forgot to build from scratch, according to instructions. Maybe we should add a warning to the docu to not use nmake or add a sample command: http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_win.html

after building with the correct generator:

```
cmake -DBUILD_TYPE=ALL -G "Visual Studio 9 2008" ..\OpenMS-2.0.1\contrib
```
I seem to get release and debug libs for all projects _except_ Wildmagic, here I only get `Wm5Core.lib` and `Wm5Mathematics.lib` but that is not a current problem for me. Still, it may be for other people and also means that I still ran into https://github.com/OpenMS/OpenMS/pull/2040

**Comment by cbielow** [comment]
Am 7/13/2016 um 2:45 AM schrieb Hannes Roest:
> yes, you are right, it works much better with the correct generator :-)
> sorry, I was so caught up in the all the problems on Windows that I
> forgot to build from scratch, according to instructions. Maybe we should
> add a warning to the docu to not use nmake or add a sample command:
> http://ftp.mi.fu-berlin.de/pub/OpenMS/develop-documentation/html/install_win.html

well, the docs clearly say:
"The <generator> you use must be one of the Visual Studio Generators. 
This is because some contrib libs require Visual Studio to build. Be 
careful to specify the Generator suffixed with "Win64" if you want a 
64bit contrib! Type $ cmake to see a list of available generators."

We can make it even more explicit and say, "i.e, DO NOT USE nmake or alike".

**Comment by hroest** [comment]
yes, we should add that to the documentation.

**Comment by jpfeuffer** [comment]
Seems to be solved. If not, it is outdated. In that case modify and reopen.
