### ISSUE TITLE
[WIN] Boost always uses VC11 toolset

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/contrib#26]
Although I specify --toolset=msvc-12.0, the bootstrap binary uses VC11. It builds but I suspect errors later on when linking to OpenMS.
Is it because it does not know about 12.0 in Boost 1.52.0?
I think we have two choices:
- Make our own toolset in the user-config.jam
- Upgrade source package (I think I read that it is definitely supported now)

What do you think? What's quicker/better?

**Comment by cbielow** [comment]
mhh... I remember there being something unintuitively weird.

If you use "--toolset=msvc" in a VS12 console, does this use VS12 then?!

(I might be wrong with this)

Am 7/14/2016 um 5:03 PM schrieb jpfeuffer:

**Comment by jpfeuffer** [comment]
Does not seem so. I will double-check. There is a comment that says that boost will take the newer msvc when you do not specify  a version number.
Maybe msvc 11 is the newest entry in the Jam files for 1.52.0.
I will actually try a newer version of boost. At least I do not need slns for it.

**Comment by jpfeuffer** [comment]
I somehow made it work some time ago. I think it was about using the correct environment AND generator AND command line.. etc.
