### ISSUE TITLE
Look at C++ Package managers

### ISSUE THREAD

**Issue by hroest** [OpenMS/contrib#27]
I wonder whether we could benefit from using an established C++ package / dependency manager. There are a few in town (https://github.com/fffaraz/awesome-cpp#build-systems):
- biicode http://biicode.github.io/biicode/
- conan https://www.conan.io/
- CPM https://github.com/iauns/cpm

**Comment by jpfeuffer** [comment]
I actually like the idea. I have a short look on them. I wonder if such managers were considered before. @OpenMS/core

**Comment by jpfeuffer** [comment]
So it seems like Conan was bought by JFrog, is actively developed with good response rates and has good chances to become a "quasi-standard". I am seriously considering starting to write some conan-files for our contrib and even the Thirdparties. They already have "recipes" for Boost, zlib, bzip and more.
The others seem like no alternative anymore.

**Comment by timosachsenberg** [comment]
I like it a lot, too. Does c++ need modules to take full advantage of this? But probably will take a while till c++ is there anyway so I would not be too much worried about that.

**Comment by hroest** [comment]
It seems like conan is really taking off, so we should have a look at it. I think it would also beat our current approach to distributing third party search engines etc.

**Comment by cbielow** [comment]
also worth discussing is maybe conda
https://gist.github.com/cbielow/039481a4e38a35977da0121d7aed116e

**Comment by jpfeuffer** [comment]
A new contender from Microsoft entered the ring:
https://github.com/Microsoft/vcpkg

**Comment by timosachsenberg** [comment]
We have vcpkg support … closing
