### ISSUE TITLE
Do we still need to support building GSL?

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/contrib#30]
Weren't all GSL dependencies removed a while ago from our libraries?
Do we need them here, still?

**Comment by timosachsenberg** [comment]
fixed in https://github.com/OpenMS/contrib/pull/31

**Comment by timosachsenberg** [comment]
and https://github.com/OpenMS/OpenMS/pull/2250

**Comment by jpfeuffer** [comment]
Okay. I will remove it from here, too.

**Comment by jpfeuffer** [comment]
Removed in #22 see also #31
