### ISSUE TITLE
zlib issue on RHEL

### ISSUE THREAD

**Issue by hroest** [OpenMS/contrib#5]
When trying to build all contrib packages I get the following error

```
$ cmake -DBUILD_TYPE=ALL .
[...]
-- Downloading ZLIB ..
-- Downloading ZLIB .. done
-- Extracting ZLIB ..
-- Extracting ZLIB .. done
-- Configuring zlib library (./configure --prefix=/scratch/hroest/openms/test/test_new_oMS2/contrib  CC=/usr/bin/cc) ..
-- Configuring zlib library (./configure --prefix=/scratch/hroest/openms/test/test_new_oMS2/contrib  CC=/usr/bin/cc) .. done
-- Building zlib library (make CC='/usr/bin/cc' CFLAGS='-Wall -O3 -fPIC') ..
-- Building zlib library (make CC='/usr/bin/cc' CFLAGS='-Wall -O3 -fPIC') .. done
-- Installing zlib library (make install) ..
-- Installing zlib library (make install) .. failed
CMake Error at libraries.cmake/zlib.cmake:146 (message):
  cp libz.a /scratch/hroest/openms/test/test_new_oMS2/contrib/lib

  cp /scratch/hroest/openms/test/test_new_oMS2/contrib/lib

  cp: missing destination file operand after
  `/scratch/hroest/openms/test/test_new_oMS2/contrib/lib'

  Try `cp --help' for more information.

  gmake: *** [install-libs] Error 1
Call Stack (most recent call first):
  CMakeLists.txt:418 (OPENMS_CONTRIB_BUILD_ZLIB)


-- Configuring incomplete, errors occurred!

```

**Comment by TorHou** [comment]
I can confirm this issue. 
BUILD_TYPE=ALL fails, BUILD_TYPE=ZLIB works.

**Comment by bjpop** [comment]
This also happens on Ubuntu 14.04.2 LTS

**Comment by poshul** [comment]
I can confirm that this is still an issue on 14.04 LTS.

**Comment by hroest** [comment]
very strange, @cbielow any idea what the issue here could be?

**Comment by hroest** [comment]
so far I have tracked the issue to this line in Makefile.in of zlib

```
171   cp $(SHAREDLIBV) $(DESTDIR)$(sharedlibdir)
```

which is the one that fails. strangely, the variable $(SHAREDLIBV) is not defined in the `Makefile` so it shows:

```
STATICLIB=libz.a
SHAREDLIB=
SHAREDLIBV=
SHAREDLIBM=
LIBS=$(STATICLIB) $(SHAREDLIBV)
```

instead of 

```
STATICLIB=libz.a
SHAREDLIB=libz.so
SHAREDLIBV=libz.so.1.2.5
SHAREDLIBM=libz.so.1
LIBS=$(STATICLIB) $(SHAREDLIBV)
```

**Comment by hroest** [comment]
also, it does not matter whether you use  BUILD_TYPE=ALL or BUILD_TYPE=ZLIB but no matter which one you use, it fails the first time and works the second time. strange. To reproduce:

```
$ git clone https://github.com/OpenMS/contrib.git && cd contrib && time cmake -DBUILD_TYPE=ZLIB 
$ time cmake -DBUILD_TYPE=ZLIB 
```

second time it works...

**Comment by poshul** [comment]
Oddly enough this only occurs the first time cmake is run. Variables are
generated properly afterwards

**Comment by hroest** [comment]
I printed out the output of configure using
```
--- a/libraries.cmake/zlib.cmake
+++ b/libraries.cmake/zlib.cmake
@@ -107,8 +107,23 @@ MACRO( OPENMS_CONTRIB_BUILD_ZLIB )
       message( FATAL_ERROR ${ZLIB_CONFIGURE_OUT})
     else()
       message( STATUS "Configuring zlib library (./configure --prefix=${CMAKE_BINARY_DIR} ${ZLIB_EXTRA_FLAGS} CC=${CMAKE_C_COMPILER}) .. done")
+      message( STATUS ${ZLIB_CONFIGURE_OUT})
     endif()
```

and oddly enough I get two different outputs when running it twice:
```
Tested /usr/bin/cc -w -c -O ztest160411.c
Tested cc -shared -O -o ztest160411.so ztest160411.o
/usr/bin/ld: ztest160411.o: relocation R_X86_64_PC32 against undefined symbol `getchar@@GLIBC_2.2.5' can not be used when making a shared object recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: ld returned 1 exit status
No shared library support try without defining CC and CFLAGS
Building static library libz.a version 1.2.5 with /usr/bin/cc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for unistd.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
```

and second time:
```
-- Checking for gcc...
Checking for shared library support...
Building shared library libz.so.1.2.5 with gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for unistd.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... Yes.
```

**Comment by poshul** [comment]
It looks like the first time the zlib configure is run there is a value defined for the variable CC, whereas subsequent runs there is not. 
`test -z "$CC" && echo Checking for ${CROSS_PREFIX}gcc...`
which causes it to fork into the "other OS" case:
`  # send working options for other systems to zlib@gzip.org
  *)         SFLAGS=${CFLAGS-"-O"}
             CFLAGS=${CFLAGS-"-O"}
             LDSHARED=${LDSHARED-"cc -shared"};;`

Leading to incorrect options being passed to cc, and compiling the shared library test without -fPIC.

I'm working on how CC gets passed in in the first place.

**Comment by hroest** [comment]
it seems that the situation is more complicated. Here is what I found so far:

1. it seems that cmake sets the CC variable (if not already set by the user)
2. on some systems, CC gets set to `/usr/bin/gcc` (ubuntu etc) on others to `/usr/bin/cc`  (red hat etc)
3. the zlib `./configure` script does a string match of the CC variable, if it contains the string "gcc" it will happily build a shared library, otherwise it will try to determine the OS and may determine that it cannot build shared libraries. Basically it does something like

```
cc=${CC-${CROSS_PREFIX}gcc}
case "$cc" in
  *gcc*) gcc=1 ;;
esac
```

The trouble is that once it determines that it does not have a gcc, it checks for all sorts of OS (but not linux* / gnu* any more) and then defaults to the "other OS" case.

There are few ways to fix this, none of which are really pretty. However, it seems that the zlib `configure` script will really produce a mess if one tries to use a non-gcc compiler on a linux system and it may be smarter to let it decide the compiler itself. Therefore one suggestion is to do 
```
set(old_CC $ENV{CC})
UNSET(ENV{CC})
[...] 
SET(ENV{CC} ${old_CC})
```
in `libraries.cmake/zlib.cmake` which at least would only affect the zlib part of the build process. This works on my system, however it overrides for all people their setting of CC and people will not able to supply their own choices any more. However, as zlib anyways does not compile with a compiler that does not contain "gcc" in its name, this is not such a big issue (e.g. `CC=clang ./configure` as well as `CC=cc ./configure` both fail while only `CC=gcc ./configure` actually works). So we basically prevent people from doing something that anyways fails and let the zlib `configure` script search for a C compiler that it likes and is happy about.

So that seems a workable solution to me.

**Comment by hroest** [comment]
apparently cmake some time ago switch from preferring /usr/bin/gcc to /usr/bin/cc  : https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=7e58e5bb

**Comment by hroest** [comment]
@poshul can you confirm #16 also works for you?

**Comment by poshul** [comment]
Yes, it works for me. Thanks
