### ISSUE TITLE
Boost build error, msvc version inconsistent

### ISSUE THREAD

**Issue by aiche** [OpenMS/contrib#8]
On behalf of @hkuich; originally reported here OpenMS/OpenMS#886

When trying to build the most recent version of contrib on windows 7, 64 bit, an error occurs reproducibly:

```
C:\Users\hkuich\Programming\contrib_build>cmake -G "Visual Studio 12 Win64" ..\c
ontrib_code -DBUILD_TYPE=BOOST
-- ADDRESSMODEL IS: 64 bit
-- MSVC Version is: 12
-- BUILD_TYPE: BOOST (one of: ALL;SEQAN;LIBSVM;XERCESC;BOOST;GSL;COINOR;BZIP2;ZL
IB;GLPK;EIGEN;WILDMAGIC)
-- FORCE_REBUILD: OFF
-- NUMBER_OF_JOBS: 2 (maximal number of concurrent compile jobs)
-- Downloading BOOST ..
-- Downloading BOOST .. skipped (already downloaded)
-- Validating archive for BOOST ..
-- Validating archive for BOOST .. done
-- Extracting BOOST ..
-- Extracting BOOST .. skipped (already exists)
-- Bootstrapping Boost libraries (bootstrap.bat) ...
-- Bootstrapping Boost libraries (bootstrap.bat) ... done
-- Building Boost library (bjam address-model=64;install;-j2;--prefix=C:/Users/h
kuich/Programming/contrib_build;--layout=tagged;--with-math;--with-date_time;--w
ith-iostreams;--with-regex;--build-type=complete;-sZLIB_SOURCE=C:/Users/hkuich/P
rogramming/contrib_build/src/zlib-1.2.5;-sBZIP2_SOURCE=C:/Users/hkuich/Programmi
ng/contrib_build/src/bzip2-1.0.5;runtime-link=shared;link=static;toolset=msvc-12
) ..
-- Building Boost library (bjam address-model=64;install;-j2;--prefix=C:/Users/h
kuich/Programming/contrib_build;--layout=tagged;--with-math;--with-date_time;--w
ith-iostreams;--with-regex;--build-type=complete;-sZLIB_SOURCE=C:/Users/hkuich/P
rogramming/contrib_build/src/zlib-1.2.5;-sBZIP2_SOURCE=C:/Users/hkuich/Programmi
ng/contrib_build/src/bzip2-1.0.5;runtime-link=shared;link=static;toolset=msvc-12
) .. failed
-- BUILD_BOOST_OUT =
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now

-- BUILD_BOOST_ERR =
-- BUILD_BOOST = 1
CMake Error at libraries.cmake/boost.cmake:80 (message):

error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now

Call Stack (most recent call first):
CMakeLists.txt:461 (OPENMS_CONTRIB_BUILD_BOOST)

-- Configuring incomplete, errors occurred!
See also "C:/Users/hkuich/Programming/contrib_build/CMakeFiles/CMakeOutput.log".
```

After modification of boost.cmake at line 62 (commenting out the TOOLSET variable as an argument), the build process proceeds and completes without errors.

```
set(BOOST_CMD_ARGS "${BOOST_ARG}" 
"install" 
"-j${NUMBER_OF_JOBS}" 
"--prefix=${PROJECT_BINARY_DIR}" 
"--layout=tagged" # create libnames without vcXXX in filename; include dir is /include/boost (as opposed to "versioned" where /include/boost-1.52/boost plus ...vc110.lib
"--with-math" 
"--with-date_time" 
"--with-iostreams" 
"--with-regex"
"--build-type=complete"
"-sZLIB_SOURCE=${ZLIB_DIR}"
"-sBZIP2_SOURCE=${BZIP2_DIR}" 
"runtime-link=shared"
"link=${BOOST_BUILD_TYPE}") 
##"${TOOLSET}")
```

However, OpenMS afterwards cannot be built, because Boost cannot be found, although the libraries are present in the `\lib` folder in contrib.

**Comment by lars20070** [comment]
Trying to install the `contrib` on Windows Server 2012 under Visual Studio 12 2013, I reproduce the error message. Running the following build command in the VS 2013 command prompt as admin
```
cmake -DBUILD_TYPE=ALL -G "Visual Studio 12 2013" .
```
results in an error message when building Boost. [Here](https://gist.github.com/lars20070/f7fec7c5b7cbdc543448619e6e163d58) the `CMakeOutput.log`.
```
-- Extracting BOOST ..
-- Extracting BOOST .. done (1st pass)
-- Extracting BOOST ..
-- Extracting BOOST .. done (2nd pass)
-- Bootstrapping Boost libraries (bootstrap.bat) ...
-- Bootstrapping Boost libraries (bootstrap.bat) ... done
-- Building Boost library (bjam address-model=64;install;-j2;--prefix=C:/Code/gi
t/contrib;--layout=tagged;--with-math;--with-date_time;--with-iostreams;--with-r
egex;--build-type=complete;-sZLIB_SOURCE=C:/Code/git/contrib/src/zlib-1.2.5;-sBZ
IP2_SOURCE=C:/Code/git/contrib/src/bzip2-1.0.5;runtime-link=shared;link=static;t
oolset=msvc-12.0) ..
-- Building Boost library (bjam address-model=64;install;-j2;--prefix=C:/Code/gi
t/contrib;--layout=tagged;--with-math;--with-date_time;--with-iostreams;--with-r
egex;--build-type=complete;-sZLIB_SOURCE=C:/Code/git/contrib/src/zlib-1.2.5;-sBZ
IP2_SOURCE=C:/Code/git/contrib/src/bzip2-1.0.5;runtime-link=shared;link=static;t
oolset=msvc-12.0) .. failed
-- BUILD_BOOST_OUT =
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now


-- BUILD_BOOST_ERR =
-- BUILD_BOOST = 1
CMake Error at libraries.cmake/boost.cmake:81 (message):


  error: msvc initialization: parameter 'version' inconsistent

  error: no value was specified in earlier initialization

  error: an explicit value is specified now



Call Stack (most recent call first):
  CMakeLists.txt:457 (OPENMS_CONTRIB_BUILD_BOOST)


-- Configuring incomplete, errors occurred!
See also "C:/Code/git/contrib/CMakeFiles/CMakeOutput.log".
```

**Comment by lars20070** [comment]
@jpfeuffer Alternatively, I can stop working with VS 2013 and use your VS 2015 branch for the installation. Shall we focus on VS 2015?

**Comment by jpfeuffer** [comment]
Let's try some quick things first:
- Can you clear the build directory of your contrib to make sure boost did not save any old configurations?
- Check that also the architecture of the generator and the command prompt you are in match. Weirdly your Generator is for 32bit builds but Boost inferred address_model=64bit.
- Try executing cmake -DBUILD_TYPE=BOOST to save time.

**Comment by jpfeuffer** [comment]
But: When I tested it, I saw that boost_1.5.2 doesn't even support msvc12. Was introduced in about 1.5.4.
So yes, maybe you test my PR instead (with matching Generator and Command Prompt architectures and a clean build dir).

**Comment by jpfeuffer** [comment]
On the other hand: Can you quickly try my suggestion and see if it starts to build, so that we can close this issue?

**Comment by lars20070** [comment]
Contrib directory cleared, build type `BOOST` and generator `Visual Studio 12 2013 Win64` lead to the same error.

Will try your VS 2015 contrib branch next ...

**Comment by jpfeuffer** [comment]
Hmm.. okay. Then this mystery bug stays.

**Comment by enetz** [comment]
I am getting the same error message on another Win 7 64bit machine with Visual Studio 12 2013 Win64,
and I think I found a way to fix it.
I did exactly the same on a Win 8.1 with VS 12 2013 Update 5 and did not encounter this problem.
Then tried it remotely on the Win 7 with the release version of VS 12 2013 and saw this error.
I then updated VS 12 2013 to Update 5 on the Win 7 machine and could compile it.

So updating Visual Studio 12 2013 to Update 5 should fix this issue.
I also restarted the computer after the installation of the update (but have not tried that before), so it could have been just that, maybe someone can confirm this?

**Comment by jpfeuffer** [comment]
Hmm.. when did you try it? Last week, the contrib was updated to a newer version of boost that supports newer MSVC versions.

**Comment by cbielow** [comment]
@enetz Thanks for the report. So bottom line is: with the latest VS update (even older VS releases), e.g. VS 12.5, the contrib compiles just fine.
I remember seeing this before for VS2008 RTM (i.e. it did not work, but Update 2 did).

We might be able to check what the Update Version of a VS is, and quit with a better error during contrib building. @enetz Can you check what CMAKE_CXX_COMPILER_VERSION is giving you on these two systems? But it might be a bit too much hassle to check this all. Instead, we could just extend the installation docs with `Make sure you have the latest updates of your VS/compiler release.`

**Comment by enetz** [comment]
@jpfeuffer thanks for the tipp, it seems the contrib was pulled before that. Just compiled the new version again and it worked fine, but can't test it without the VS update.

@cbielow After the VS update on the second system, the version on both is: MSVC 18.0.40629.0
(works for the old and new contrib version)
Before the update the second system had VS2013 RTM Pro
(did not work with the old contrib, not tested with new contrib)

**Comment by jpfeuffer** [comment]
Can not reproduce anymore. Reopen if you can.
