### ISSUE TITLE
error compiling COINOR on Mac Os 10.9 (from clean VM)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/contrib#9]
``` 
 In file included from CoinIndexedVector.cpp:14:

  ./CoinTypes.hpp:10:11: fatal error: 'cinttypes' file not found

  # include <cinttypes>

            ^

  1 error generated.

  make[2]: *** [CoinIndexedVector.lo] Error 1

  make[2]: *** Waiting for unfinished jobs....

  CoinLpIO.cpp:1272:17: warning: format string is not a string literal
  (potentially insecure) [-Wformat-security]

    sprintf(buff, start_str)
                  ^~~~~~~~~

  CoinLpIO.cpp:1371:22: warning: format string is not a string literal
  (potentially insecure) [-Wformat-security]

    sprintf(start_str, buff)
                       ^~~~

  2 warnings generated.

  make[1]: *** [all-recursive] Error 1

  make: *** [all-recursive] Error 1
Call Stack (most recent call first):
  CMakeLists.txt:491 (OPENMS_CONTRIB_BUILD_COINOR)


-- Configuring incomplete, errors occurred!
```

**Comment by hroest** [comment]
do we still need Coinor in OpenMS? or would this be a good point to kick it out?

**Comment by cbielow** [comment]
depends, if you have big problem instances COINOR makes a lot of sense.

On the other hand, maintaining two solver libs is overhead...



Am 3/18/2015 um 3:14 PM schrieb Hannes Roest:

**Comment by aiche** [comment]
The better question is, do we need glpk since it is gpl licensed

**Comment by cbielow** [comment]
true,
COIN-MP is EPL [1], which is compatible with BSD [2]

So any reson to keep glpk?

[1] 
https://projects.coin-or.org/CoinMP/browser/releases/1.8.0/CoinMP/LICENSE
[2] https://eclipse.org/legal/eplfaq.php#COMPILEWOMOD


Am 3/18/2015 um 16:45 schrieb Stephan Aiche:

**Comment by timosachsenberg** [comment]
Probably related to a mac issue: https://github.com/Homebrew/homebrew/issues/20635

**Comment by timosachsenberg** [comment]
also note that cinttypes seems to be c11

**Comment by jpfeuffer** [comment]
https://bugs.launchpad.net/gearmand/+bug/1358084

This patch solves it for me. Await PR.
